name: Code Quality & Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Fix Node.js deprecation warnings
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff mypy radon bandit pytest

      - name: Lint with ruff
        run: ruff check report_engine
      - name: Lint with mypy
        run: mypy --install-types
        run: mypy report_engine
      - name: Lint with radon
        run: radon cc report_engine | grep  '[C-F]$'
      - name: Lint with bandit
        run: bandit bandit -r  report_engine
      - name: Run tests
        run: pytest -q
