name: SLSA Provenance

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: write

jobs:
  build:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.9.0
    with:
      base64-subjects: ""
